apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vote-back-{{.Values.serviceName}}
spec:
  replicas: {{ .Values.back.ReplicaCount }}
  template:
    metadata:
      labels:
        app: vote-back-{{.Values.serviceName}}
    spec:
      containers:
      - name: vote-back-{{.Values.serviceName}}
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vote-front-{{.Values.serviceName}}
spec:
  replicas: {{ .Values.front.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: vote-front-{{.Values.serviceName}}
    spec:
      containers:
      - name: azure-vote-front
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: vote-back-{{.Values.serviceName}}
        - name: TITLE
          value: {{ .Values.title }}
        - name: VOTE1VALUE
          value: {{ .Values.value1 }}
        - name: VOTE2VALUE
          value: {{ .Values.value2 }}

# Add if operator to env vars
