apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}-vote-back
  labels:
    name: {{.Values.serviceName}}-vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: {{.Values.serviceName}}-vote-back
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    name: {{ .Values.serviceNameFront }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 80
  selector:
    app: {{.Values.serviceName}}-vote-front
