apiVersion: v1
kind: Service
metadata:
  name: vote-back-{{.Values.serviceName}}
  labels:
    name: vote-back-{{.Values.serviceName}}
spec:
  ports:
  - port: 6379
  selector:
    app: vote-back-{{.Values.serviceName}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    name: {{ .Values.serviceNameFront }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 80
  selector:
    app: vote-front-{{.Values.serviceName}}
